version: "3.9"

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arcadia_flask
    env_file:
      - .env

    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MONGO_URI=${MONGO_URI}
    restart: always
